forum/urls.py
from django.conf.urls import url
from .views import index, add_message, dashboard, clear, update_comment
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message/(?P<id>.*)/$', add_message, name='add_message'),
	url(r'^dashboard/$', dashboard, name='dashboard'),
	
	url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear'),
	url(r'^update_comment/(?P<pk>[0-9]+)', view=update_comment, name='update_comment'),
	# custom auth
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

jobnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import t3_profile.urls as t3_profile
import forum.urls as forum
import login.urls as login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(t3_profile, namespace='profile')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='login/', permanent='true')),
]

t3_profile/urls.py
from django.conf.urls import url
from .views import index, process_profile

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^process_profile', process_profile, name='process_profile'),
]

t3_profile/models.py
from django.db import models

# Create your models here.

t3_profile/views.py
from django.shortcuts import render
from login.views import response as respon 
from django.views.decorators.csrf import csrf_exempt
response = {}

def index(request):
	response['author'] = "Kelompok 15 PPW"
	return render(request, "t3_profile/t3_profile.html", response)
    
@csrf_exempt
def process_profile(request):
    response['type'] = request.POST.get('type')
    response['name'] = request.POST.get('name')
    response['id'] = request.POST.get('id')
    response['descriptions'] = request.POST.get('description', '')
    response['weburl'] = request.POST.get('weburl', '')
    response['imgurl'] = request.POST.get('logourl', '')
    response['specialties'] = request.POST.get('specialties', '')
    return render(request, 't3_profile/t3_profile_for_ajax.html', response)

t3_profile/templates/t3_profile/partials/header.html
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="{% url 'profile:index' %}">Perusahaan</a>
	</div>
	<div id="navbar" class="navbar-collapse collapse">
	  <ul class="nav navbar-nav">
		<!-- LINK MENUJU table, dan link menuju home#form -->
		<li><a href="#"> Dashboard </a></li>
		<li><a href="{% url 'profile:index' %}"> Profile </a></li>
		<li><a href="#"> Forum </a></li>
		<li><a href="#"> Cari Mahasiswa </a></li>
	  </ul>
	  <ul class="nav navbar-nav navbar-right">
		<li><a href="#"><span class="glyphicon glyphicon-user"></span> Perusahaan Something </a></li>
		<li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Logout </a></li>
	  </ul>
	</div>
  </div>
</nav>