forum/urls.py
from django.conf.urls import url
from .views import index, add_message, dashboard, clear, update_comment
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_message/(?P<id>.*)/$', add_message, name='add_message'),
	url(r'^dashboard/$', dashboard, name='dashboard'),
	
	url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear'),
	url(r'^update_comment/(?P<pk>[0-9]+)', view=update_comment, name='update_comment'),
	# custom auth
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

jobnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import t3_profile.urls as t3_profile
import forum.urls as forum
import login.urls as login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(t3_profile, namespace='profile')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^$', RedirectView.as_view(url='login/', permanent='true')),
]

login/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    ]

forum/models.py
from django.db import models

# Create your models here.
class Pengguna(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
    nama = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Message(models.Model):
	pengguna = models.ForeignKey(Pengguna)
	title = models.CharField(max_length=140)
	message = models.TextField()
	kode_message = models.CharField("Kode Message", max_length=50)
	created_date = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
	message = models.ForeignKey(Message, null=True, blank=True)
	comment = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)


    

login/models.py
from django.db import models

# Create your models here.

forum/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    title_attrs = {
        'class': 'form-control',
        'placeholder':'This post is about...'
    }

    message_attrs = {
        'class': 'form-control',
        'placeholder':'Your post is...'
    }

    title = forms.CharField(label='Judul Forum', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=message_attrs), required=True)

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs ={
        'type': 'text',
        'cols': 60,
        'rows': 10,
        'class': 'comment-form-textarea',
        'placeholder':' Write your comment here. . '
    }
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

forum/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Message_Form, Comment_Form
from .models import Message, Pengguna, Comment
from .utils import *

# Create your views here.
response = {}
def index(request):
    # print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('forum:dashboard'))
    else:
        response['author'] = get_data_user(request, 'user_login')
        html = 'login.html'
        return render(request, html, response)

def dashboard(request):
    
    if not 'user_login' in request.session.keys():
        return HttpResponseRedirect(reverse('forum:index'))
    else:
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)

        message = Message.objects.filter(pengguna=pengguna)
        
        response['message'] = message
        response['message_form'] = Message_Form
        response["message_list"] = message
        comments = Comment.objects.all()
        
        response['comments'] = comments
        response['comment_form'] = Comment_Form
        html = 'forum.html'
        
        message_list = message
        paginator = Paginator(message_list, 5)
        page = request.GET.get('page', 1)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)
       
        response["message_list"] = users
        html = 'forum.html'
        return render(request, html, response)

def add_message(request, id):
    response['id'] = id
    form = Message_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        kode_identitas = get_data_user(request, 'kode_identitas')
        try:
            pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
        except Exception as e:
            pengguna = create_new_user(request)  
     
        response['title'] = request.POST['title'] 
        response['message'] = request.POST['message']
        message = Message(pengguna=pengguna,title=response['title'], message=response['message'], kode_message = id)
        message.save()
        response['id'] = id
        html ='forum.html'    
        return HttpResponseRedirect('/forum/')

def update_comment(request,pk):
    update = Message.objects.get(pk=pk)
    form = Comment_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['comment'] = request.POST['comment']
        comments = Comment(comment=response['comment'])
        comments.update = update
        comments.save()
        return HttpResponseRedirect('/forum/')
    else:
        return HttpResponseRedirect('/forum/')

def clear(request,object_id):
    clears = Message.objects.get(pk=object_id)
    clears.delete()
    return HttpResponseRedirect('/forum/')

def paginate_page(page, data_list):
    paginator = Paginator(data_list, 3)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 3 else 0
    end_index = 3 if index < max_index - 3 else max_index
    # Get our new page range. In the latest versions of Django page_range returns
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

response = {}
def index(request):
    html = 'login/login.html'
    return render(request, html, response)

forum/templates/forum.html
{% extends "general/layout/base.html" %}
{% load staticfiles %}
{% load static %}


{% block navbar_user %}
<li><a href="#"><span class="glyphicon glyphicon-user" id="nama-perusahaan-header"></span></a></li>
<li><a href="#"><span class="glyphicon glyphicon-log-out" id="navbar-logout-btn"></span> Logout </a></li>
{% endblock %}


{% block title %}
  Forum Lowongan
{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
  <style>
    .desain_footer{
      position: absolute;
    }
  </style>
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid text-center" style="margin-bottom: 0px; margin-top: 0px; background-color: #F1F7ED">
  <div class="container">
    <h1 class="display-3" style="font-family: Impact;">Forum Diskusi Lowongan Kerja</h1>
  </div>
</div>

<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'forum:add_message' id %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>


{% if message_list %}
{% for data in message_list %}
  <section name="update-status" id="update-status">
      <div class = "status">
          <div class="row">
              <div class="col-sm-12 col-sm-offset-0">
                <div class="media" style="padding: 15px">
                  <div class="media-left">
                  </div>
                  <div class="media-body">
                      <strong>{{data.title}} </strong>
                      <h6>Posted on {{data.created_date}}</h6>
                      <p>{{data.message}}</p>
                      <div class="delete" data-id="{{data.id}}">
                        <a href="{% url 'forum:clear' object_id=data.id %}"><img src="https://png.icons8.com/full-trash/androidL/1600" style="width: 35px;height 35px; top: 10px;"></a>
                      </div>
                  </div>
                </section>
                  <section name="update-comment" id="update-comment">
                    {% for comment in comments %}
                      <div class = "comment">
                            <div class="row">
                              <div class="col-sm-8 col-sm-offset-0">
                                <div class="media" style="padding: 8px">
                                  <div class="media-left">
                                  </div>
                                  <div class="media-body">
                                    <strong>Reply</strong>
                                    <h6>Posted on {{comment.created_date}}</h6>
                                    <p>{{comment.comment}}</p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                      </div>
                    {% endfor %}
                  </section>
                    <section name="popupBoxPosition" id="popupBoxPosition">
                      <div class="popupBoxWrapper">
                        <div class="popupBoxContent">
                          <form id="form" method="POST" action="{% url 'forum:update_comment' pk=data.id %}">
                            <h2>Add Comment</h2>
                            <br>
                            {% csrf_token %}
                            {{ comment_form }}
                            <br>
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Post Comment">
                          </form>
                        </div>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
{% endfor %}
{% else %}
    <div class="alert alert-danger text-center">
                <strong>Maaf!</strong> Tidak ada forum
            </div>
{% endif %}

{% if message_list.has_other_pages %}
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}

<script type="text/javascript">
  <!--
   function toggle_visibility(id) {
    var e = document.getElementById(id);
    if(e.style.display == 'block')
     e.style.display = 'none';
    else
     e.style.display = 'block';
   }
  //-->
</script>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
var onLinkedInLoad = function() {
    console.log(IN.User.isAuthorized());
    if (IN.User.isAuthorized() === false) {window.location.replace('/login/');} else {
    IN.API.Raw("/companies?format=json&is-company-admin=true").result(function(comps){
        console.log(comps), comp_data = comps.values[0], comp_id = comp_data.id, IN.API.Raw("/companies/" + comp_id + ":(id,name,ticker,description)?format=json").result(function(data_comp) {
        
        $("#header-user-login").append('<li><a href="#"><span class="glyphicon glyphicon-user" id="nama-perusahaan"></span>'+data_comp.name+'</a></li><li><a id="navbar-logout-btn"><span class="glyphicon glyphicon-log-out" id="navbar-logout-btn"></span> Logout </a></li>');
        $("#navbar-logout-btn").on("click", user_log_out);
        $("#navbar-logout-btn").css("cursor", "pointer");
        console.log(data_comp);
        });
    });
    }
};

var user_log_out = function() {
    IN.User.logout(function(o) {
        console.log(o);
        window.location.replace('/login/')
    });
};
    </script>
    
{% endblock %}

forum/templates/login.html
{% extends "layout/base.html" %}

{% block header %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
      </ul>
      
    </div>


  </div><!-- /.container-fluid -->
</nav>  
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'forum:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}